import React, { useRef } from 'react';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';
import { ShieldCheck, AlertTriangle, Activity, Download } from 'lucide-react';
import { Card } from './Card';

const ReportCard = ({ report }) => {
  const containerRef = useRef();

  useGSAP(() => {
    gsap.fromTo(
      containerRef.current.children,
      { y: 20, opacity: 0 },
      { y: 0, opacity: 1, duration: 0.6, stagger: 0.1, ease: 'power2.out' }
    );
  }, []);

  if (!report) return null;

  const isHigh = report.risk_level === 'high';
  const isMed = report.risk_level === 'medium';
  const riskColor = isHigh ? 'text-red-500' : isMed ? 'text-orange-500' : 'text-green-500';
  const riskBg = isHigh ? 'bg-red-50 border-red-100' : isMed ? 'bg-orange-50 border-orange-100' : 'bg-green-50 border-green-100';
  const RiskIcon = isHigh ? AlertTriangle : isMed ? Activity : ShieldCheck;

  return (
    <div ref={containerRef} className="space-y-6 max-w-4xl mx-auto">
      <div className="flex justify-between items-center bg-white p-6 rounded-2xl border border-slate-200/50 shadow-sm">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">Diagnostic Analysis</h2>
          <p className="text-slate-500 text-sm">Generated by More to Heal AI • Today</p>
        </div>
        <button className="btn-secondary flex items-center gap-2 group">
          <Download className="w-4 h-4 group-hover:-translate-y-1 transition-transform" />
          Download PDF
        </button>
      </div>

      <div className={`p-8 rounded-2xl border flex items-center gap-6 ${riskBg}`}>
        <div className={`p-4 bg-white rounded-2xl shadow-sm ${riskColor}`}>
          <RiskIcon className="w-10 h-10" />
        </div>
        <div className="flex-1">
          <div className="text-sm font-bold uppercase tracking-wider mb-1" style={{ color: isHigh ? '#dc2626' : isMed ? '#ea580c' : '#16a34a' }}>
            {report.risk_level} Risk Level
          </div>
          <h3 className="text-3xl font-extrabold text-slate-800">{report.condition}</h3>
        </div>
        <div className="text-right bg-white px-6 py-4 rounded-2xl shadow-sm">
          <div className="text-sm text-slate-500 font-medium">Confidence Score</div>
          <div className="text-2xl font-black text-slate-800">{report.confidence}</div>
        </div>
      </div>

      <Card>
        <h4 className="text-xl font-bold text-slate-800 mb-4 pb-4 border-b border-slate-100">Clinical Overview</h4>
        <p className="text-slate-600 text-lg leading-relaxed">{report.description}</p>
      </Card>

      <div className="grid md:grid-cols-2 gap-6">
        <Card className="bg-gradient-to-br from-white to-slate-50 border-slate-200">
          <h4 className="flex items-center gap-3 text-lg font-bold text-slate-800 mb-6">
            <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-primary">
              <ShieldCheck className="w-4 h-4" />
            </div>
            Precautions
          </h4>
          <ul className="space-y-4">
            {report.precautions.map((item, i) => (
              <li key={i} className="flex gap-3 text-slate-600">
                <span className="text-primary font-bold mt-0.5">•</span> 
                <span className="leading-relaxed">{item}</span>
              </li>
            ))}
          </ul>
        </Card>

        <Card className="bg-gradient-to-br from-white to-slate-50 border-slate-200">
          <h4 className="flex items-center gap-3 text-lg font-bold text-slate-800 mb-6">
            <div className="w-8 h-8 rounded-full bg-highlight/10 flex items-center justify-center text-highlight">
              <Activity className="w-4 h-4" />
            </div>
            Recommended Actions
          </h4>
          <ul className="space-y-4">
            {report.recommended_actions.map((item, i) => (
              <li key={i} className="flex gap-3 text-slate-600">
                <span className="text-highlight font-bold mt-0.5">•</span> 
                <span className="leading-relaxed">{item}</span>
              </li>
            ))}
          </ul>
        </Card>
      </div>
    </div>
  );
};

export default ReportCard;
